import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footer from "../components/sections/footer";
import Navigation from "../components/sections/navigation";
import CommandPalette from "../components/headlessUiComponents/modal";
import AppLayoutAuth from ".";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Beegee Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppLayoutAuth>
          <Navigation/>
          {children}
          <Footer/>
          <CommandPalette/>
          
        </AppLayoutAuth>
      </body>
      
    </html>
  );
}
